#!/bin/csh
#
# compile -- compile the Yale Haskell system from scratch.
#
#
cd $Y2
$LUCID <<EOF
;; To get Lucid's development mode compiler, remove (compilation-speed 0)
(make-package "MUMBLE-IMPLEMENTATION" :use '("LISP"))
(proclaim '(optimize (speed 3) (safety 0) (compilation-speed 0)))
(load "cl-support/cl-init")
(quit)
EOF
