#!/bin/csh
#
# compile -- compile the Yale Haskell system from scratch.
#
#
cd $Y2
$LISPWORKS <<EOF
(load "com/lispworks/patches/safe-fo-closure.wfasl")
(make-package "MUMBLE-IMPLEMENTATION" :use '("LISP"))
(proclaim '(optimize (speed 3) (safety 0) (compilation-speed 0)))
(load "cl-support/cl-init")
(lw:bye)
EOF
