#!/bin/csh
#
# build-prelude -- recompile the prelude, saving the old one as old-prelude.*
#
#
cd $Y2
setenv PRELUDEBIN $Y2/progs/prelude/$ALLEGRODIR
if (-e $PRELUDEBIN/Prelude.fasl) then
  rm $PRELUDEBIN/old*
  foreach i ($PRELUDEBIN/Prelude*.{fasl,scm})
    mv $i $PRELUDEBIN/old-$i:t
    end
  endif
$ALLEGRO <<EOF
;; Need a big heap to compile the prelude.
;;(lcl:change-memory-management :expand 512 :growth-limit 2048)
#+next (progn (load "com/allegro/next-patches/patch0149.fasl")
              (load "com/allegro/next-patches/patch0151.fasl"))
#+sparc (load "com/allegro/sparc-patches/patch0151.fasl")
(make-package "MUMBLE-IMPLEMENTATION" :use '("LISP"))
(proclaim '(optimize (speed 3) (safety 0) (compilation-speed 0)))
(load "cl-support/cl-init")
(in-package :mumble-user)
(setf *printers* '(phase-time dump-stat))
(setf *optimizers* *all-optimizers*)
;; Set appropriate compiler settings for processing the prelude.
;; Don't try to compile the interface.
(setf *code-chunk-size* 300)
(setf *compile-interface* '#f)
(compile/compile *prelude-unit-filename*)
(excl:exit)
EOF
